name: Dependabot checks
on: pull_request

permissions: write-all

jobs:
  dependabot:
    name: dependabot
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          make ci-test

